### ISSUE TITLE
Criar visualização personalizada da assinatura

### ISSUE THREAD

**Issue by icaropires** [pbad-pades/pades-plugin#70]
Criar visualização da assinatura com as informações do assinante semelhante à seguinte:

![formato assinatura](https://user-images.githubusercontent.com/18473249/47947128-82f13600-def5-11e8-9a3c-2d6561701d72.png)

**Comment by josutk** [comment]
![aparencia](https://user-images.githubusercontent.com/19808747/53583387-401c3380-3b60-11e9-8daa-113886826c07.PNG)


Aparência adotada para a assinatura até  o momento
